FROM ubuntu:trusty

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=bitconnect/bitconnect
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY bitconnect.tar.gz /bitconnect.tar.gz
RUN tar -xvf /bitconnect.tar.gz

#xenial
#Missing requirement: libtool
#RUN apt install -yqq libtool-bin
RUN cd /bitconnect/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /bitconnect && scripts/windows-crosscompile/compile-bitconnect.sh
